# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI\addEditCoffeeForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class AddEditCoffeeForm(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(502, 447)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.delete_button = QtWidgets.QPushButton(Form)
        self.delete_button.setObjectName("delete_button")
        self.gridLayout.addWidget(self.delete_button, 1, 3, 1, 1)
        self.save_button = QtWidgets.QPushButton(Form)
        self.save_button.setObjectName("save_button")
        self.gridLayout.addWidget(self.save_button, 1, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 4, 1, 1)
        self.tabs = QtWidgets.QTabWidget(Form)
        self.tabs.setObjectName("tabs")
        self.coffee = QtWidgets.QWidget()
        self.coffee.setObjectName("coffee")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.coffee)
        self.gridLayout_2.setContentsMargins(0, -1, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.coffee_table = QtWidgets.QTableWidget(self.coffee)
        self.coffee_table.setObjectName("coffee_table")
        self.coffee_table.setColumnCount(0)
        self.coffee_table.setRowCount(0)
        self.gridLayout_2.addWidget(self.coffee_table, 0, 0, 1, 1)
        self.tabs.addTab(self.coffee, "")
        self.roasting = QtWidgets.QWidget()
        self.roasting.setObjectName("roasting")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.roasting)
        self.gridLayout_3.setContentsMargins(0, -1, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.roasting_table = QtWidgets.QTableWidget(self.roasting)
        self.roasting_table.setObjectName("roasting_table")
        self.roasting_table.setColumnCount(0)
        self.roasting_table.setRowCount(0)
        self.gridLayout_3.addWidget(self.roasting_table, 0, 0, 1, 1)
        self.tabs.addTab(self.roasting, "")
        self.state = QtWidgets.QWidget()
        self.state.setObjectName("state")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.state)
        self.gridLayout_4.setContentsMargins(0, -1, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.state_table = QtWidgets.QTableWidget(self.state)
        self.state_table.setObjectName("state_table")
        self.state_table.setColumnCount(0)
        self.state_table.setRowCount(0)
        self.gridLayout_4.addWidget(self.state_table, 0, 0, 1, 1)
        self.tabs.addTab(self.state, "")
        self.gridLayout.addWidget(self.tabs, 0, 0, 1, 5)
        self.load_button = QtWidgets.QPushButton(Form)
        self.load_button.setObjectName("load_button")
        self.gridLayout.addWidget(self.load_button, 1, 0, 1, 1)
        self.add_button = QtWidgets.QPushButton(Form)
        self.add_button.setObjectName("add_button")
        self.gridLayout.addWidget(self.add_button, 1, 2, 1, 1)

        self.retranslateUi(Form)
        self.tabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Капучино"))
        self.delete_button.setText(_translate("Form", "Удалить"))
        self.save_button.setText(_translate("Form", "Сохранить"))
        self.tabs.setTabText(self.tabs.indexOf(self.coffee), _translate("Form", "Кофе"))
        self.tabs.setTabText(self.tabs.indexOf(self.roasting), _translate("Form", "Степень обжарки"))
        self.tabs.setTabText(self.tabs.indexOf(self.state), _translate("Form", "Состояние"))
        self.load_button.setText(_translate("Form", "Открыть"))
        self.add_button.setText(_translate("Form", "Добавить"))
